In [50]:
# Numpy arrays use contigious memeory as compared to python's lists


# python lists are slower compared to numpy arrays


In [51]:
import numpy as np

# creating numPy arrays

#1 from existing lists 

list1 = [1 , 2 , 3 , 4]
arr1 = np.array(list1)
print(arr1)
print()

arr2 = np.array([[1 , 2 , 4]  , [8  , 9 , 7] , [1 , 5 , 2]])
print(arr2)
print()
#2 using placeholder functions (when u have the shape u need)

print(np.zeros((2 , 3)))
print()
print(np.ones((3 , 2)))
print()

print(np.arange(10 , 20 , 2)) # similar to range function but returns an array from ascending to descending


print()

# 3) random method

print(np.random.rand(3 , 3))
print()
# random generates random numbers
# rand lets random function generate number between interval of [0 , 1]

print(np.random.uniform(5 , 10 , (2 , 2)))
print()
# uniform(low, high, size): "Uniform" just means every number between the low and high has an equal chance of being picked.



print()
print(arr1.ndim)
# ndim is a property thats why no parenthesis
#.ndim: Number of dimensions (1 for a list, 2 for a table).

print(arr2.shape)
# shape = (rows , columns)
print(arr2.size)
# size = rows * columns

print(arr1.dtype)
#dtype property lets u check the datatype

print(np.array([1 , 2 , 3 ,4] , dtype = 'float32'))
#we are setting the datatype during creation

arr1type = arr1.astype(float) #another way to manipulate with datatype using astype function
print(arr1type)

[1 2 3 4]

[[1 2 4]
 [8 9 7]
 [1 5 2]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[10 12 14 16 18]

[[0.87756119 0.63761384 0.18830158]
 [0.88757349 0.59870707 0.42532679]
 [0.33939231 0.49224119 0.43392996]]

[[9.21364007 5.61618013]
 [5.56403144 9.33564283]]


1
(3, 3)
9
int64
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [ ]:
import pandas as pd


data = {
    'Advertising_Budget': [50, 45, 60, 55, 65],
    'Sales_across_months': [200, 180, 250, 230, 270]
}

df = pd.DataFrame(data)

print(df.cov)
print(df.cor    )

<bound method DataFrame.cov of    Advertising_Budget  Sales_across_months
0                  50                  200
1                  45                  180
2                  60                  250
3                  55                  230
4                  65                  270>


AttributeError: 'DataFrame' object has no attribute 'cor'

In [ ]:
# QUESTION

# Create a numpy array ArrayNum with 5 rows and 5 columns to store random numbers from 1 to 50

print(np.random.uniform(1 , 51 , (5 , 5)))
print()
print(np.random.randint(1 , 51 , (5 , 5))) # preferred

# unlike unifrom which gives random decimal values , rand makes sure it only gives integer values



[[13.08893079 33.52303125 12.2220884   2.58038011 19.37687765]
 [ 4.29682611 44.21308739 30.43522415 27.66700438 27.96290332]
 [13.01127668  2.51793808 37.60261972 39.54811068 10.03622933]
 [21.8429848   3.24892411  6.26083987 25.35803072  9.56456274]
 [21.22508276 15.23276723  9.41499766 43.82689219 37.38113238]]

[[48 48 43 29 36]
 [12  9 22 49 45]
 [10  4 38 43 33]
 [38 49 23 39  2]
 [29  3  3 29  3]]


In [ ]:
# indexing and slicing

# SLICING FORMULA : 
#array[row_start : row_stop, col_start : col_stop]

# the stop index is excusive i.e if u take :3 , THEN IT SLICES 0 , 1 and 2



arr = np.array([[1 , 2 , 4]  , [8  , 9 , 7] , [1 , 5 , 2]])
print()

print(arr[1, :]) # selects row-1 and all columns 
print(arr[: , 2]) # selects all rows and 2nd column of each row
print(arr[0:2 , 0: 2])

# NEGATIVE INDEXING

# -1 is the last element and -2 is the 2nd last element

print()
print(arr[-2: , 1])


[8 9 7]
[4 7 2]
[[1 2]
 [8 9]]

[9 5]


In [ ]:
# How would you write the code to get the "Bottom Right $2 * 2$ block"?


arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

print(arr[-2: , -2:])

[[110 120]
 [150 160]]


In [ ]:
# INDEXING AND SLICING QUESTIONS


data_matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

#a) Last two elements of the 2nd column.

print(data_matrix[-2 : , 1])

#b) Four elements from the Bottom right

print(data_matrix[-2:, -2:])

# c) First two elements of the 3rd row.

print(data_matrix[2 , 0: 2])

# d)Entire 4th column.

print(data_matrix[ : , 3])

# e) All elements in the top-left $3 \times 3$ block. 

print(data_matrix[0:3 , 0:3])

[100 140]
[[110 120]
 [150 160]]
[ 90 100]
[ 40  80 120 160]
[[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]]


In [ ]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

print(arr[1][0:2])        # Output A
print(arr[1:3, 1:3])      # Output B
print(arr[1:, 1:])        # Output C
print(arr[1:2, 2])

        # Output D

arr[1:2, 1:2] = 0         # Modification
print(arr)                # Output E

[40 50]
[[50 60]
 [80 90]]
[[50 60]
 [80 90]]
[60]
[[10 20 30]
 [40  0 60]
 [70 80 90]]


In [ ]:
challenge_arr = np.arange(36).reshape(6, 6)
print(challenge_arr[: , :])
print(challenge_arr[2: 4 , 2: 4])
print(challenge_arr[:: -1 , ::-1]) # reversing using numpy slicing by using the 3rd input which is step


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[14 15]
 [20 21]]
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [ ]:
# SWAPPING AXES AND TRANSPOSING ARRRAY

# TRANSFOSING FN SIMPLY TRANSPOSES AN ARRAY

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(arr.T)

# we use the "T" property to transpose an array

# Syntax: arr.swapaxes(axis1, axis2)

# HERE AXIS-0 IS ROWS AND AXIS-1 IS COLUMNS

# swapaxes(0 , 1) is the same as arr.T

## RESHAPING ARRAY ##

# i.e the process of changing the dimensions of array without changing its data

# RULE :  The total number of elements must stay the same. 


# ex : 4 * 4 = 8 * 2 OR 1 * 16

# QUES )Convert a2d [4x4] into a three-dimensional numpy array a3d of size 2x4x2

# ANS : a3d = a2d.reshape(2 , 4 , 2)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# QUESTION


x = np.array([[1, 2, 3], [4, 5, 6]]) 
y = np.array([10, 20, 30])

z = x + y

print(z.shape) # remains 2 x 3

print(z.swapaxes(1 , 0).shape)

(2, 3)
(3, 2)


In [ ]:
#DATA PROCESSING I.E MATHEMATICAL OPERATIONS AND STSTAISTICAL ANALYSIS USING NUMPY

## CALCULATING STATISTICS ACCROSS PARTS OF ARRARS USING AXIS ##

# AXIS = 0 : LETS U TAKE CONTOLL OF THE OPERATIONS HAPPENING DOWN THE COLUMNS

# AXIS = 1 : LETS YOU TAKE CONTROL OF OPERATIONS HAPPENING DOWN THE ROWS



arr = np.array([[1, 2, 3], 
                [4, 5, 6]])


row_means = arr.mean(axis=1)
row_std = arr.std(axis=1)

column_means = arr.mean(axis = 0)

print(row_means)

print(row_std)
print(column_means)


# Broadcasting allows NumPy to perform arithmetic on arrays of different shapes, provided they follow these rules:

# If the arrays have a different number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

# If the shape of the two arrays does not match in any dimension, the array with a shape equal to 1 in that dimension is stretched to match the other shape.

[2. 5.]
[0.81649658 0.81649658]
[2.5 3.5 4.5]


In [ ]:
import numpy as np


arr = np.array([[1, 2, 3], 
                [4, 5, 6] , 
                [7 , 8 , 9] , 
                [5 , 8 , 10]])


print(arr[0:2, :])
print(arr[:, 1])
print(arr[arr > 5])

print(arr.swapaxes(2 , 1))

print()



print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

print()

print(np.full((4 , 3) , 5))

print()

print(np.arange(0 , 10 , 2)) # stop does not count , these are evenly spaced values

print(np.linspace(0, 10, 5)) # the third argument evenly sapces the values if i want 5 values then it generates 5 evenly spacesd values b/w start and stop

print()

print(np.random.rand(1 , 5)) # float
print(np.random.randint(1 , 5 , 3)) # int but has a third arg as no of values

 

[[1 2 3]
 [4 5 6]]
[2 5 8 8]
[ 6  7  8  9  8 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  8 10]]

(4, 3)
2
12
int64
8

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]

[[0.510674   0.23584475 0.85906783 0.49223298 0.22986474]]
[3 1 2]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])


[[ 1  2  3]
 [99  5  6]]


In [57]:
print(np.zeros((2 , 3 , 4)).swapaxes(0 , 2))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
